using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace PleasantvilleGame
{
   public partial class ShowIconDisplayDialog : Window
   {
      public ShowIconDisplayDialog()
      {
         InitializeComponent();
         Thickness thickness = new Thickness(0, 8, 0, 0);
         int row = -1;
         int col = 0;
         Image img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("IconFireInsteadOfMove"), Margin = thickness};
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("IconMoveInsteadFire") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() {Height=50, Width=40, IsEnabled=false, Source = MapItem.theMapImages.GetBitmapImage("IconContinueMove") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("IconRearFacing") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 40, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("IconInterdiction") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("IconWeather") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 40, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("IconHidden") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 40, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("IconThrownTrack") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("OApHit") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("OHeHit") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("OBogged") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         //--------------------------------------------
         row = -1;
         col = 2;
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("OBoggedStuck"), Margin = thickness};
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("OWoods") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("OBuild") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("OFort") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("OSPOT") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("OHIDE") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("OINC") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("OUNC") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("OMIA") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("OKIA") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("ThrownTrack") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         //--------------------------------------------
         row = -1;
         col = 4;
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("ShermanLead"), Margin = thickness};
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("Fuel") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("FuelEmpty") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("RankCaptain") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("RankFirstLieutenant") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("RankSecondLieutenant") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("RankStaffSergeant") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("RankSergeant") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("AirStrike") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("Alert1") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("Alert5") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         //--------------------------------------------
         row = -1;
         col = 6;
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("Alert3"), Margin = thickness};
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("Alert2") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("WeatherClear") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false,  Source = MapItem.theMapImages.GetBitmapImage("WeatherOvercast") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("WeatherMud") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("WeatherMudOvercast") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("WeatherRain") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("WeatherMudRain") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("WeatherFog") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("WeatherSnowGround") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("WeatherSnowDeep") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         //--------------------------------------------
         row = -1;
         col = 8;
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("WeatherSnowFalling"), Margin = thickness};
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("WeatherSnowFallingGround") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("WeatherSnowFallingDeep") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("DecorationMedalOfHonor") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("DecorationBronzeStar") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("DecorationSilverStar") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("DecorationDistinguishedCross") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("DecorationPurpleHeart") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("DecorationEasternCampaign") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
         img = new Image() { Height = 50, Width = 40, IsEnabled = false, Source = MapItem.theMapImages.GetBitmapImage("DecorationVictoryMedal") };
         myGrid.Children.Add(img);
         Grid.SetRow(img, ++row);
         Grid.SetColumn(img, col);
      }
      private void ButtonOk_Click(object sender, RoutedEventArgs e)
      {
         Close();
      }
   }
}
